---
plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - exe/*
    - spec/**/*

Gemspec/RequireMFA:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/Alias:
  EnforcedStyle: prefer_alias_method
